### ISSUE TITLE
Genuine difference in sampler performance for bizzare(?) `seeds_data-seeds_model`

### ISSUE THREAD

**Issue by JasonPekos** [JasonPekos/TuringPosteriorDB.jl#9]
So, `seeds_model`, a hierarchical mixed effects model for counts, has different sampler performance in Stan and Turing despite what looks to be a correct model implementation (unless I'm missing something ...).

**Turing Draws:**
```
Summary Statistics
  parameters      mean       std      mcse   ess_bulk   ess_tail      rhat   ess_per_sec 
      Symbol   Float64   Float64   Float64    Float64    Float64   Float64       Float64 

      alpha0    0.0051    5.3374    0.3170   282.0490   350.1422    1.0010        9.1963
      alpha1   -3.1013    7.5044    0.5660   175.0573   309.8876    1.0007        5.7078
      alpha2    1.0549    7.6087    0.3779   410.2692   434.0699    1.0019       13.3769
     alpha12    2.0795   11.1756    0.6607   297.7086   393.5594    1.0104        9.7068
         tau    0.0080    0.0031    0.0002   374.8287   653.7758    1.0080       12.2213
       sigma   11.8057    2.4338    0.1266   374.8287   653.7758    1.0080       12.2213
```

**Stan Draws:**

```
Summary Statistics
  parameters      mean        std      mcse    ess_bulk    ess_tail      rhat   ess_per_sec 
      Symbol   Float64    Float64   Float64     Float64     Float64   Float64       Missing 

      alpha0   -0.5483     0.1878    0.0045   1728.1558   1632.0473    1.0015       missing
      alpha1    0.0912     0.3110    0.0085   1346.2091   2058.6790    1.0036       missing
     alpha12   -0.8233     0.4323    0.0109   1552.0613   1907.5411    1.0035       missing
      alpha2    1.3471     0.2711    0.0065   1735.6467   2265.2837    1.0014       missing
         tau   55.4729   120.5225   11.9704    128.9584    162.2965    1.0222       missing
       sigma    0.2738     0.1420    0.0116    128.9588    162.2965    1.0222       missing
```

Note especially the difference in `tau` and `sigma`.

### in Stan (`seeds_model.stan` in PDB):

```stan
data {
  int<lower=0> I;
  array[I] int<lower=0> n;
  array[I] int<lower=0> N;
  vector[I] x1;
  vector[I] x2;
}
transformed data {
  vector[I] x1x2;
  x1x2 = x1 .* x2;
}
parameters {
  real alpha0;
  real alpha1;
  real alpha12;
  real alpha2;
  real<lower=0> tau;
  vector[I] b;
}
transformed parameters {
  real<lower=0> sigma;
  sigma = 1.0 / sqrt(tau);
}
model {
  alpha0 ~ normal(0.0, 1.0E3);
  alpha1 ~ normal(0.0, 1.0E3);
  alpha2 ~ normal(0.0, 1.0E3);
  alpha12 ~ normal(0.0, 1.0E3);
  tau ~ gamma(1.0E-3, 1.0E-3);
  
  b ~ normal(0.0, sigma);
  n ~ binomial_logit(N,
                     alpha0 + alpha1 * x1 + alpha2 * x2 + alpha12 * x1x2 + b);
}
```

### Seeds Model in Turing `seeds_model.jl`:
```julia
using Turing
using FillArrays

@model function seeds_model(I, n, N, x1, x2; x1x2 = x1 .* x2)
    alpha0 ~ Normal(0.0, 1.0e3)
    alpha1 ~ Normal(0.0, 1.0e3)
    alpha2 ~ Normal(0.0, 1.0e3)
    alpha12 ~ Normal(0.0, 1.0e3)
    tau ~ Gamma(1.0e-3, 1.0e-3)
    sigma := 1.0 / sqrt(tau)

    # Use UniformScaling because data already contains `I`
    b ~ MvNormal(fill(0.0, I), UniformScaling(sigma^2))
    n .~ Turing.BinomialLogit.(N, alpha0 .+ alpha1 .* x1 .+ alpha2 .* x2 .+ alpha12 .* x1x2 .+ b)
end
```

## What's going on?

I think the problem comes from the use of the `tau ~ gamma(1.0E-3, 1.0E-3)` prior. This is essentially a point mass at zero, and then a long `FlatPos()` tail over the positive real numbers. I don't really know *why* this was chosen as a prior, but it seems like Turing is getting "stuck" at zero, while Stan is not.

---

I don't know if this indicates a problem to be fixed or anything like that, but I thought I'd keep a record of which models are behaving weird. CC: @sethaxen.

**Comment by JasonPekos** [comment]
Same thing going on with the Dugongs model

**Comment by sethaxen** [comment]
Ah, this is a common footgun. There are multiple parameterizations of the Gamma distribution, which makes it really confusing in papers and code when it's not explicitly stated which is used. You have either the shape-scale parameterization $(\alpha, \beta)$ or the shape-rate parameterization $(k, \theta)$, where $k=\alpha$ and $\beta = 1/\theta$. From looking at the densities, [Stan uses shape-scale](https://mc-stan.org/docs/functions-reference/positive_continuous_distributions.html#gamma-distribution), while [Distributions.jl uses shape-rate](https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.Gamma), so try `tau ~ Gamma(1.0e-3, 1.0e3)`.

**Comment by JasonPekos** [comment]
Ah, thanks! I'll get this fixed 🫡 .
